jobs:
  detekt:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: detekt
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Run detekt
      run: bash ./gradlew detekt
  spotless:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: Spotless (ktlint)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Run spotless
      run: bash ./gradlew spotlessCheck
name: Analysis
on:
  repository_dispatch:
    types: trigger-ga___analysis.yml
permissions: read-all
