jobs:
  apk:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: Generate APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build debug APK
      run: bash ./gradlew assembleDev --stacktrace
    - continue-on-error: true
      name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-dev-debug
        path: News-Android-App/build/outputs/apk/dev/debug/News-Android-App-dev-debug.apk
  lint:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: Run Lint Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Lint
      run: bash ./gradlew lint
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: Run Unit Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Unit tests
      run: bash ./gradlew test --stacktrace
  validation:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name
      != github.event.pull_request.base.repo.full_name
    name: Validate Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
